### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by SmallCookier** [SilvioGiancola/TrackingNet-devkit#16]
I download the data. but I have follow problem.such as:

"Downloading the data files for the following chunks"
CHUNKS: ['TRAIN_11']
DATA: ['ZIPS', 'ANNO']
"TRAIN_11_ZIPS:   0%|                                                        | 0/2511 [00:00<?, ?it/s]"

Traceback (most recent call last):
  File "download_TrackingNet.py", line 95, in <module>
    data=args.data)
  File "download_TrackingNet.py", line 43, in main
    quiet=True,
  File "/home/edison/projects/TrackingNet/downloader.py", line 58, in download
    res = sess.get(url, stream=True)
  File "/home/edison/anaconda3/envs/TrackingNet/lib/python3.6/site-packages/requests/sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "/home/edison/anaconda3/envs/TrackingNet/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/edison/anaconda3/envs/TrackingNet/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/edison/anaconda3/envs/TrackingNet/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=19nyc6XXx3Px7OgLjrPDtsN3T7UUz5woI (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1552b8bb00>: Failed to establish a new connection: [Errno 110] Connection timed out',))

Is this my own problem? or Server issues？
Looking forward to your reply!

**Comment by SilvioGiancola** [comment]
That looks like a problem on your side. See #2 for more details
