### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by davidparkerhl** [SilvioGiancola/TrackingNet-devkit#6]
after running for a minute and downloading 14 files i got this 

`python download_TrackingNet.py --trackingnet_dir trackingnet 
Downloading the data files for the following chunks
CHUNKS: ['TEST', 'TRAIN_0', 'TRAIN_1', 'TRAIN_2', 'TRAIN_3', 'TRAIN_4', 'TRAIN_5', 'TRAIN_6', 'TRAIN_7', 'TRAIN_8', 'TRAIN_9', 'TRAIN_10', 'TRAIN_11']
DATA: ['ANNO', 'ZIPS']
TEST_ANNO:   0%|                                        | 0/511 [00:00<?, ?it/s]
TEST_ANNO:   3%|▊                              | 14/511 [00:07<04:26,  1.86it/s]
Traceback (most recent call last):
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1632, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 448, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=17kTfdOsoVH1MCJ0QWfQcn1-OwaOaAugM (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidparker/Desktop/code/data/TrackingNet-devkit/download_TrackingNet.py", line 96, in <module>
    data=args.data)
  File "/Users/davidparker/Desktop/code/data/TrackingNet-devkit/download_TrackingNet.py", line 44, in main
    quiet=True,
  File "/Users/davidparker/Desktop/code/data/TrackingNet-devkit/downloader.py", line 58, in download
    res = sess.get(url, stream=True)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=17kTfdOsoVH1MCJ0QWfQcn1-OwaOaAugM (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')",),))
Exception ignored in: <bound method tqdm.__del__ of TEST_ANNO:   3%|▊                              | 14/511 [01:07<04:26,  1.86it/s]>
Traceback (most recent call last):
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/Users/davidparker/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/Users/davidparker/anaconda3/lib/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
Davids-MacBook-Pro:TrackingNet-devkit davidparker$ `

**Comment by SilvioGiancola** [comment]
Hi @davidparkerhl what happen if you run the code again? is it a recurrent error?

**Comment by SilvioGiancola** [comment]
It appears to me that the issue has been solved.
